# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: |
    (?x)^(
        InvenTree/InvenTree/static/.*|
        InvenTree/locale/.*|
        src/frontend/src/locales/.*|
        .*/migrations/.*
    )$
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: mixed-line-ending
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2
    hooks:
    - id: ruff-format
      args: [--preview]
    - id: ruff
      args: [
        --fix,
        --preview
      ]
-   repo: https://github.com/matmair/ruff-pre-commit
    rev: 830893bf46db844d9c99b6c468e285199adf2de6  # uv-018
    hooks:
      - id: pip-compile
        name: pip-compile requirements-dev.in
        args: [requirements-dev.in, -o, requirements-dev.txt, --python-version=3.9]
        files: ^requirements-dev\.(in|txt)$
      - id: pip-compile
        name: pip-compile requirements.txt
        args: [requirements.in, -o, requirements.txt,--python-version=3.9]
        files: ^requirements\.(in|txt)$
-   repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.34.1
    hooks:
      - id: djlint-django
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.6
  hooks:
  - id: codespell
    exclude: >
      (?x)^(
          docs/docs/stylesheets/.*|
          docs/docs/javascripts/.*|
          docs/docs/webfonts/.* |
          src/frontend/src/locales/.* |
      )$
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: "v4.0.0-alpha.8"
  hooks:
    - id: prettier
      files: ^src/frontend/.*\.(js|jsx|ts|tsx)$
      additional_dependencies:
      - "prettier@^2.4.1"
      - "@trivago/prettier-plugin-sort-imports"
- repo: https://github.com/pre-commit/mirrors-eslint
  rev: "v9.0.0-beta.0"
  hooks:
  - id: eslint
    additional_dependencies:
      - eslint@^8.41.0
      - eslint-config-google@^0.14.0
      - eslint-plugin-react@6.10.3
      - babel-eslint@6.1.2
      - "@typescript-eslint/eslint-plugin@latest"
      - "@typescript-eslint/parser"
    files: ^src/frontend/.*\.(js|jsx|ts|tsx)$
