name: Check Translations

on:
  push:
    branches:
      - l10
  pull_request:
    branches:
      - l10

env:
  python_version: 3.9

jobs:

  check:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      INVENTREE_DB_NAME: './test_db.sqlite'
      INVENTREE_DB_ENGINE: django.db.backends.sqlite3
      INVENTREE_DEBUG: info
      INVENTREE_MEDIA_ROOT: ./media
      INVENTREE_STATIC_ROOT: ./static
      INVENTREE_BACKUP_DIR: ./backup

    steps:
      - name: Checkout Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # pin@v4.1.1
      - name: Environment Setup
        uses: ./.github/actions/setup
        with:
          install: true
          apt-dependency: gettext
      - name: Test Translations
        run: invoke translate
      - name: Check Migration Files
        run: python3 ci/check_migration_files.py
